import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Lato } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import BackgroundPattern from "@/components/BackgroundPattern";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Zeema Homes",
  description: "Generated by create next app",
};

import Providers from "@/components/Providers";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased",)}
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icon-512.png" />
          <meta name="mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-status-bar-style" content="default" />
          <meta name="apple-mobile-web-app-title" content="Zeema Home" />
          <meta name="theme-color" content="#09A9F8" />
        </head>
      <body className={`w-full min-h-full flex justify-center font-(--font-lato) bg-white py-6`}>
        <div className="w-full max-w-7xl bg-transparent relative px-4 md:px-0">
          <BackgroundPattern />
          <Header />
          <Providers>
            {children}
          </Providers>
        </div>
        </body>
    </html>
  );
}
