import Header from "@/components/Header";
import Hero from "@/components/homepage/Hero";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page | Zeema Homes",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="min-h-screen">
      <Hero />
    </main>
  );
}
